#!/bin/bash

set -e

NODE_NAME=${NODE_NAME:-"$(hostname)"}
BOOTSTRAP_EXPECT=${BOOTSTRAP_EXPECT:-"1"}

SERVER=${SERVER:-"FALSE"}
SERVER_ARGS=""

if [[ $SERVER == "TRUE" ]]; then
  SERVER_ARGS="-server --bootstrap-expect=${BOOTSTRAP_EXPECT}"
fi

exec /usr/bin/consul agent -bind=0.0.0.0 -client=0.0.0.0 -config-dir=/etc/consul.d -data-dir=/var/lib/consul -node=${NODE_NAME} ${SERVER_ARGS}
