#!/bin/bash

set -e

NODE=$(hostname -s)
if [[ $NODE_NAME != "localhost" ]]; then
  NODE=$NODE_NAME
fi

SERVER_ARGS=""
if [[ $SERVER == "TRUE" ]]; then
  SERVER_ARGS="-server --bootstrap-expect=${BOOTSTRAP_EXPECT}"
fi

JOIN_ARGS=""
if [[ $JOIN_CLUSTER == "TRUE" ]]; then
  JOIN_ARGS="-join=$JOIN_ADDR"
fi

exec /usr/bin/consul agent -bind=$BIND_ADDR -client=$CLIENT_ADDR -config-dir=/etc/consul.d -data-dir=/var/lib/consul -node=${NODE} ${SERVER_ARGS} ${JOIN_ARGS}
